### ISSUE TITLE
Implement a SSB dbgen extension

### ISSUE THREAD

**Issue by arnenator** [Tietgen-ITU/advanced-data-systems#23]
# What is this about?
We need a way to easily create schemas and generate data for those schemas. Luckily this has already been done for us. Pinar has implemented a library that we can use to generate this specifically for SSB benchmarks.

### Tasks:
- [x] Create a directory under `extensions` called `ssb`
- [x] Copy and paste(with a credit to the author of course!) the code from [Pinar's repo](https://github.itu.dk/pito/ads2024-ssb-dbgen). Take what we can use.
- [x] Implement integration between the Pinar's code and duckdb
- [x] Test - See that it works
