### ISSUE TITLE
Investigate the different approaches to implementing the benchmark suite

### ISSUE THREAD

**Issue by arnenator** [Tietgen-ITU/advanced-data-systems#24]
# What is this issue about?

Since there are different implementations we need to investigate how they are implemented and the reason why they are implemented in that way. In the project description they recommend looking into TPC-H and Clickbench.

### Tasks
- [x] How do we run the experiments?
- [x] What is the difference between TPC-H and Clickbench?
   - [x] Why has TPC-H been implemented with `c++`
   - [x] Why is `clickbench` only sql and `.in` files
- [x] Explain why you choose a specific implementation and create a detail plan of implementation

**Comment by arnenator** [comment]
This is done
